### ISSUE TITLE
Interest in joining TidierOrg?

### ISSUE THREAD

**Issue by kdpsingh** [TheRoniOne/Cleaner.jl#10]
Hi @TheRoniOne, there is a lot of interest in your package from the TidierData.jl user community because it's a core dependency for us.

While janitor, the R package that inspired Cleaner.jl, isn't technically part of the tidyverse, we would be happy to bring Cleaner into TidierOrg if you're interested since it's closely linked to the tidyverse ecosystem. Potentially this would give it more visibility and help bring additional contributors.

If we did so, we would leave the name of the package unchanged, and you would retain control of the package. I realize this package supports a broader set of Tables.jl interfaces and not just DataFrames.jl -- none of that would need to change.

If you're not interested, no worries! Feel free to close the issue.

**Comment by TheRoniOne** [comment]
I truly appreciate the offer, but at the time being I'm not as active as I once was in the Julia ecosystem as by now I'm only mostly maintaining this package so I will have to decline.

Feel free to continue opening issues if you find any bugs (that I will try to fix with priority) or ask for new features.
