### ISSUE TITLE
Should polish_names also remove apostrophes ? 

### ISSUE THREAD

**Issue by yolhan83** [TheRoniOne/Cleaner.jl#11]
Hello, 
I recently encountered an issue while using the @clean_names function in TiderData.jl. It seems that the function doesn't remove apostrophes, which is problematic for my current use case. Could you please add a functionality to handle this? I think replacing apostrophes with underscores (_) would be an acceptable solution. 
Thank you for your assistance.

**Comment by TheRoniOne** [comment]
Released version 1.0.5 fixing this issue
