### ISSUE TITLE
Column named `BMI` gets converted to `b_m_i` instead of `bmi`

### ISSUE THREAD

**Issue by kdpsingh** [TheRoniOne/Cleaner.jl#12]
More details here: https://github.com/TidierOrg/TidierData.jl/issues/79

**Comment by kdpsingh** [comment]
Bumping for visibility. Thank you for taking a look.

**Comment by TheRoniOne** [comment]
Fixed on v1.0.6.

 As a friendly reminder, taking a look to the code takes almost no time and anyone can draft a fix and send a PR like this [one](https://github.com/TheRoniOne/Cleaner.jl/commit/89e8aa30682266fdaf6a4bf65e44433926586f6e).

**Comment by kdpsingh** [comment]
Thank you for fixing. In the future, will try to chip in and help with PRs.
