### ISSUE TITLE
Extending the polish_names() function

### ISSUE THREAD

**Issue by CyuHat** [TheRoniOne/Cleaner.jl#14]
Hi!
Thank you for your nice package. I think it is a nice and useful implementation janitor in Julia.

As a Follow up to the [conversation](https://github.com/TidierOrg/TidierData.jl/issues/97) I had with kdpsingh from the TidierData.jl package, I wanted to know if you are open to improve the `polish_names()` function in your package to match some specificities of the `janitor::clean_names()` function from R. Mainly the following points:

- Removing/replacing accents (à, é, ô, ...)
- Removing single and double quotes
- Removing various brackets
- Replacing "%" by "percent"
- Replacing "#" by "number"
- Removing other special characters ("!", ",", "$", ...)
- Appending numbers to duplicate names (if needed)

I am still a beginner, but I can give a hand for the implementation as it will help me gain more experiences with Julia.

**Comment by TheRoniOne** [comment]
Fixed on version 1.1.0, [check my PR](https://github.com/TheRoniOne/Cleaner.jl/pull/15/files) for the details on how I did it if you are interested.
