### ISSUE TITLE
Join efforts into TableTransforms.jl?

### ISSUE THREAD

**Issue by juliohm** [TheRoniOne/Cleaner.jl#3]
Hi @TheRoniOne , what a coincidence, we announced two packages that have very similar goals. What do you think of joining efforts in TableTransforms.jl to achieve better *revertibility* and a common API?

https://github.com/JuliaML/TableTransforms.jl

We are actively working on the package, and many more transforms will be added in the following days. Our API is extremely simple to implement, and we would certainly benefit from the cleaning transforms you have added here.

Let me know what do you think, it would be nice to avoid duplication of work, and think more generally in terms of transforms as opposed to just data cleaning.

**Comment by TheRoniOne** [comment]
I'm definitely interested on upstreaming my work on `Cleaner.jl` as a dependency into `TableTransforms.jl`, while keeping `Cleaner.jl` as a minimal dependency too (currently `Cleaner.jl` only depends on Tables.jl v"1" and PrettyTables v"1" so there should't be any compatibility problems).

Thanks to following semver, all minor `Cleaner.jl` releases should be directly compatible and available with the latest version of `TableTransforms.jl` and I will personally upstream all new features on major `Cleaner.jl` releases to follow your API while also updating the Cleaner entry on `TableTransforms.jl`'s Project.toml if you are fine with it too.

I will also develop tests for all new features upstreamed from `Cleaner.jl` to `TableTransforms.jl` to ensure nothing breaks.

Would be great to coordinate major `Cleaner.jl` and `TableTransforms.jl` releases too to have all latest features on `Cleaner.jl` always be available on the latest version of `TableTransforms.jl`.

If you agree, please let me know so I can start developing pull requests towards `TableTransforms.jl` repo.
