### ISSUE TITLE
Minor snakecase parsing issue

### ISSUE THREAD

**Issue by kdpsingh** [TheRoniOne/Cleaner.jl#5]
Thank you for this wonderful package. We currently wrap it in TidierData.jl.

One of our users noticed that a column named `Vehicle_ID` gets converted to `vehicle_i_d` when it is converted to snake case instead of `vehicle_id` (which is how R's janitor handles it).

Is this something you would be interested (and have the bandwidth) to investigate/change/fix?

https://github.com/TidierOrg/TidierData.jl/issues/25

Thanks again.

- Karandeep

**Comment by TheRoniOne** [comment]
Thank you for the kind words, happy that my package is being helpful.

**Comment by TheRoniOne** [comment]
Thank you for the kind words, I'm happy that my package is being useful.

Just managed to solve this bug and I'm making a new patch release solving it.

**Comment by TheRoniOne** [comment]
Should be working as expected now on v1.0.2 (already released too)

**Comment by kdpsingh** [comment]
Thank you!
