### ISSUE TITLE
Updating dependency versions

### ISSUE THREAD

**Issue by kdpsingh** [TheRoniOne/Cleaner.jl#6]
Currently, Cleaner.jl depends on Tables (version == "1") and PrettyTables (version == "1).

However, because DataFrames.jl relies on PrettyTables v2.1, Cleaner.jl currently forces DataFrames.jl to be downgraded to quite an older version (v1.3.6) in order for these requirements to be satisfied.

Can we change the compat for PrettyTables to version == "2" or "1, 2" if you want to allow for v1 as well?

Thanks for considering.

**Comment by kdpsingh** [comment]
Just bumping this. Thanks for taking a look.

**Comment by TheRoniOne** [comment]
Thanks for letting me know, just released v1.0.3 fixing this issue.
