### ISSUE TITLE
Bug: Need to remove "/" from column names

### ISSUE THREAD

**Issue by kdpsingh** [TheRoniOne/Cleaner.jl#9]
It looks like R janitor's `clean_names()` function removes "/" from column names, whereas `Cleaner.polish_names()` does not.

See here for a reproducible example: https://github.com/TidierOrg/TidierData.jl/issues/52

Would be great to fix this to match the janitor package's behavior.

**Comment by TheRoniOne** [comment]
Just released version 1.0.4 fixing this issue
